package com.company.models.categories;

public enum Category {
    ACCESORIES,
    BEAUTYANDHEALTH,
    CELLPHONES,
    COMPUTERS,
    VIDEOGAMESANDCONSOLES,
    CONSTRUCTION,
    ELECTRONICS,
    TOOLS,
    HOMEFURNITUREANDGARDEN,
    INDUSTRIESANDOFFICES,
    INDOORS,
    INSTRUMENTS,
    JEWERLYANDWATCHES,
    GAMESANDTOYS,
    BOOKSANDCOMICS,
    MUSICANDMOVIES,
    CLOTHINGANDACCESORIES,
    HEALTHANDMEDICEQUIPMENT,
    SERVICES,
    PARTIES,
    OTHER
}
